---
- hosts: "{{ variable_hosts | default('jberts') }}"
  become: true


  pre_tasks:
    - name: Check for local application config file
      local_action: stat path={{ jbert_config_file }}
      become: false
      register: local_config_file
    - fail:
        msg: "Configuration file {{ jbert_config_file }} not found"
      when: local_config_file.stat.exists == False

    - name: Creates a temporary directory
      file:
        path: '{{ jbert_tmp_dir }}'
        state: directory


  tasks:
    - name: Copy jbert deb to the temporary directory
      copy:
        src: '{{ local_jbert_deb_package }}'
        dest: '{{ jbert_tmp_dir }}/{{ local_jbert_deb_package }}'

    - name: Stop application
      systemd:
        name: '{{ jbert_application_name }}'
        state: stopped

    - name: Remove application package
      apt:
        name: '{{ jbert_application_name }}'
        purge: yes
        state: absent

    - name: Install application package
      apt:
        deb: '{{ jbert_tmp_dir }}/{{ local_jbert_deb_package }}'
        state: present

    - name: Change jbert application file permissions
      file:
        path: '{{ jbert_application_root }}'
        owner: '{{ jbert_application_user }}'
        recurse: yes

    - name: Remove application PID file
      file:
        path: /usr/share/jbert/RUNNING_PID
        state: absent

    - name: Copy application.conf if existing
      copy:
        src: '{{ jbert_config_file }}'
        dest: '/usr/share/jbert/conf/application.conf'
        owner: '{{ jbert_application_user }}'
        follow: true
        force: true

    - name: Reload application
      systemd:
        name: '{{ jbert_application_name }}'
        enabled: yes
        state: restarted


  post_tasks:
    - name: Remove temporary directory
      file:
        path: '{{ jbert_tmp_dir }}'
        state: absent
